---
title: "Libro de códigos"
subtitle: 'Estudio "Meritocracia y Redistribución"'
author: "Fondecyt regular N°1160921"
output: 
  bookdown::pdf_document2:
    toc: false  
geometry: "left=0.1cm,right=1cm,top=2cm,bottom=2cm"      
editor_options: 
  chunk_output_type: console
header-includes:
  - \usepackage[spanish,es-tabla,es-nodecimaldot]{babel}
  - \usepackage{times}           # Times New Roman
  - \usepackage{caption}
  - \captionsetup[figure, table]{labelfont={bf},labelformat={default},labelsep=period}
  - \usepackage{graphicx}
  - \usepackage{float}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
classoption: [landscape, legalpaper]
fontsize: 10
---

```{r render, eval=FALSE, include=FALSE}
# si no tenemos la librería pacman instalada, se instala.
if (!require("pacman")) install.packages("pacman") 
# instalar librerias rmarkdown, bookdown y here 
pacman::p_load(rmarkdown,bookdown,here)
# renderizar documento
rmarkdown::render(input = here::here("padsoc-template/02-documentacion/libro-codigo.Rmd"),
                  output_dir = here::here("padsoc-template/03-publicacion"))
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,# mostrar advertencias durante la generación del libro de códigos
  message = FALSE,# mostrar mensajes durante la generación del libro de códigos
  error = FALSE,  # no interrumpir la generación del libro de códigos en caso de errores,
                  # suele ser mejor para la depuración
  echo = FALSE    # mostrar el código R
  )

def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
```

```{r}
if (!require("pacman")) install.packages("pacman") 
pacman::p_load(dplyr, #librerias del tidyverse
               haven,
               here,
               sjmisc) 
```

# Ola 1

```{r, size="tiny"}
load(here::here("padsoc-template/01-datos/study_w01.RData"))
sjmisc::frq(study_w01,
            min.frq = 10
            )
```


