# <i class="fa fa-folder-open" aria-hidden="true"></i>  Proyecto/ {-}

La **apertura** de datos puede resumirse en tres momentos. Primero, la identificación de la complejidad del estudio a través de la descripción del diseño de investigación. Segundo, la preparación y documentación de la base de datos. Tercero, el proceso de organización de cada archivo necesario para la publicación de los datos. 


Cada uno de estos momentos se traduce en una estructura digital de carpetas que contienen cada pieza de información: 

* <i class="fa fa-folder-open" aria-hidden="true"></i>   Datos
    - Preparación 
      - Datos brutos (archivos)
      - Procesamiento (código: organización, nombres y etiquetado de variables)
    - Datos a publicar (archivos)
    - Metadatos (p.ej. cita bibliográfica, manual de usuario)
  
* <i class="fa fa-folder-open" aria-hidden="true"></i>  Documentación
    - Preparación de documentación de datos
      - Preparación libro de códigos
      - Preparación ficha técnica
      - Preparación instrumentos de recolección de información
      
* <i class="fa fa-folder-open" aria-hidden="true"></i>   Publicación

    - Checklist para publicación (checklist.pdf)
    - Datos (p.ej: study_01.RData)
    - Metadatos (user-manual.pdf)
    - Libro de código (codebook.pdf)
    - Ficha técnica (ficha-tecnica.pdf)
    - Instrumentos (cuestionario_study_01.pdf)



    
    

    
