## <i class="fa fa-file-text" aria-hidden="true"></i> Descripción (README) {-}

La complejidad de una base de datos constituye un reflejo del diseño de investigación del estudio al cual pertenecen. Por este motivo, identificar las características de un estudio de manera precisa contribuye a establecer lo que debemos esclarecer antes de poner a disposición nuestros datos antes la comunidad de pares y a la sociedad en general. Al respecto, la Tabla \@ref(tab:tab-strat) establece una ejemplo minimalista respecto a cómo es posible clasificar un estudio cuantitativo según el tipo de diseño.     

```{r tab-strat, echo=FALSE}
pacman::p_load(readxl,knitr,kableExtra,dplyr)
table_1 <- read_excel(here::here("input/tables/table-1.xlsx"))

table_1 %>% 
  kable(caption = "Estrategias de inferencia causal", 
        col.names = "Diseño") %>% 
  kable_styling(font_size = 12) %>% 
  footnote("Traducción propia en base a (Gerring, 2012; p. 257) ",footnote_as_chunk = T) %>% 
  row_spec(c(1,3,5), bold = T) %>% 
  add_indent(c(2, 4, 6))
```

En referencia a lo anterior, teniendo un marco de referencia respecto a la complejidad de nuestro estudio, podemos proyectar las siguientes tareas a realizar para **describir**, **documentar** y **publicar** nuestros datos.

A continuación presentaremos el esquema del protocolo en base a las tres subcarpetas principales: Datos, Documentación y Publicación.



