---
title: "Libro de códigos"
subtitle: 'Estudio "Meritocracia y Redistribución"'
author: "Fondecyt regular N°1160921"
output: 
  bookdown::pdf_document2:
    toc: false  
geometry: "left=0.1cm,right=1cm,top=2cm,bottom=2cm"      
editor_options: 
  chunk_output_type: console
header-includes:
  - \usepackage[spanish,es-tabla,es-nodecimaldot]{babel}
  - \usepackage{times}           # Times New Roman
  - \usepackage{caption}
  - \captionsetup[figure, table]{labelfont={bf},labelformat={default},labelsep=period}
  - \usepackage{graphicx}
  - \usepackage{float}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
classoption: [landscape, legalpaper]
fontsize: 10
---

```{r render, eval=FALSE, include=FALSE}
# si no tenemos la librería pacman instalada, se instala.
if (!require("pacman")) install.packages("pacman") 
# instalar librerias rmarkdown, bookdown y here 
pacman::p_load(rmarkdown,bookdown,here)
# renderizar documento
rmarkdown::render(input = here::here("padsoc-template/plantillas/libro-codigo/libro-codigo.Rmd"),
                  output_dir = here::here("padsoc-template/documentacion"))
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,# mostrar advertencias durante la generación del libro de códigos
  message = FALSE,# mostrar mensajes durante la generación del libro de códigos
  error = FALSE,  # no interrumpir la generación del libro de códigos en caso de errores,
                  # suele ser mejor para la depuración
  echo = FALSE    # mostrar el código R
  )

def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
```

```{r}
if (!require("pacman")) install.packages("pacman") 
pacman::p_load(dplyr, #librerias del tidyverse
               haven,
               here) 
```

# Ola 1


<!-- PASO 0: cargar datos -->
```{r}
data <- read_sav(here::here("padsoc-template/datos/ola1/Estudio_3_ola1.sav"))
```

<!-- PASO 1: reordenar variables -->
```{r include=FALSE}
# Reorganizar variables:
  
df_w1 <- data %>% 
  select(ResponseId,ticket,
         Finished,Progress,
         Intro,
         # preguntas: importancia para salir adelante
         starts_with("get_ah"),
         # Orden - Display Order (DO): importancia para salir adelante
         starts_with("get_ah_DO"),
         # preguntas: escala percepcion y preferencia meritocracia
         starts_with("meritv01_"), # items bloque 1
         merit_perc_scale,
         Q3_1,
         Q4_1,
         starts_with("meritv02_"), # items bloque 2
         merit_perc_scale.0,
         Q205_1,
         Q206_1,
         starts_with("meritv03_"), # items bloque 3
         merit_perc_scale.1,
         Q209_1,
         Q210_1,
         # preguntas: salario percibido y justo:
         sal_perc_1,sal_perc_2,
         sal_just_1,sal_just_2,
         # Percepcion de pobreza:
         percep_pov,
         # preguntas: politicas y sociodemograficos
         pospol_1,
         # preguntas: escala de igualitarismo
         starts_with("egal_"), 
         # Orden - Display Order (DO): escala de igualitarismo
         starts_with("igualitarismo_DO"),
         edad,sexo,educat,edcep,ingresos,
         ess01_1,ess02_1,ess03_1,
         estlab,comuna,
         # informacion de respuesta online
         "StartDate","EndDate",
         "Duration__in_seconds_",
         "RecordedDate",
         "IPAddress",         
         "Status",
         "RecipientLastName",
         "RecipientFirstName",
         "RecipientEmail",
         "ExternalReference",
         "LocationLatitude",
         "LocationLongitude",
         "DistributionChannel",
         "UserLanguage",
         # pertenencia a bloques aleatorizados:
         "FL_21_DO_merit_perc_pref_julio19v01",# bloque 1
         "FL_21_DO_merit_perc_pref_julio19v02",# bloque 2
         "FL_21_DO_merit_perc_pref_julio19v03" # bloque 3 
         )
```

```{r eval=FALSE, include=FALSE}
names(df_w1)
names(data)
```

```{r echo=FALSE}
variable_label <-
  sjlabelled::get_label(df_w1) %>% 
  data.frame()


knitr::kable(variable_label,
             col.names = "Etiqueta",
             format = "html",
             booktabs=T) %>% 
  kableExtra::kable_styling(full_width = F,
                            latex_options = "scale_down") %>% 
  kableExtra::column_spec(column = 2,width = "10cm")
```

```{r, size="tiny"}
sjmisc::frq(df_w1,
            min.frq = 10
            )
```


