---
title: "Preparacion de datos"
subtitle: 'Estudio "Meritocracia y Redistribución"'
author: "Fondecyt regular N°1160921"
output: 
  html_document:
    toc: true  
editor_options: 
  chunk_output_type: console
fontsize: 10
---

```{r render, eval=FALSE, include=FALSE}
# si no tenemos la librería pacman instalada, se instala.
if (!require("pacman")) install.packages("pacman") 
# instalar librerias rmarkdown, bookdown y here 
pacman::p_load(rmarkdown,bookdown,here)
# renderizar documento
rmarkdown::render(input = here::here("padsoc-template/99-plantillas/prep_data.Rmd"))
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,# mostrar advertencias durante la generación del libro de códigos
  message = FALSE,# mostrar mensajes durante la generación del libro de códigos
  error = FALSE,  # no interrumpir la generación del libro de códigos en caso de errores,
                  # suele ser mejor para la depuración
  echo = FALSE    # mostrar el código R
  )
```

```{r}
if (!require("pacman")) install.packages("pacman") 
pacman::p_load(dplyr, #librerias del tidyverse
               haven,
               here) 
```

# Ola 1

```{r prep-wave01, include=FALSE}
# PASO 1: Cargar datos
data <- read_sav(here::here("padsoc-template/99-plantillas/input/Estudio_3_ola1.sav"))
# PASO 2: reordenar variables
study_w01 <- data %>% 
  select(ResponseId,ticket,
         Finished,Progress,
         Intro,
         # preguntas: importancia para salir adelante
         starts_with("get_ah"),
         # Orden - Display Order (DO): importancia para salir adelante
         starts_with("get_ah_DO"),
         # preguntas: escala percepcion y preferencia meritocracia
         starts_with("meritv01_"), # items bloque 1
         merit_perc_scale,
         Q3_1,
         Q4_1,
         starts_with("meritv02_"), # items bloque 2
         merit_perc_scale.0,
         Q205_1,
         Q206_1,
         starts_with("meritv03_"), # items bloque 3
         merit_perc_scale.1,
         Q209_1,
         Q210_1,
         # preguntas: salario percibido y justo:
         sal_perc_1,sal_perc_2,
         sal_just_1,sal_just_2,
         # Percepcion de pobreza:
         percep_pov,
         # preguntas: politicas y sociodemograficos
         pospol_1,
         # preguntas: escala de igualitarismo
         starts_with("egal_"), 
         # Orden - Display Order (DO): escala de igualitarismo
         starts_with("igualitarismo_DO"),
         edad,sexo,educat,edcep,ingresos,
         ess01_1,ess02_1,ess03_1,
         estlab,comuna,
         # informacion de respuesta online
         "StartDate","EndDate",
         "Duration__in_seconds_",
         "RecordedDate",
         "IPAddress",         
         "Status",
         "RecipientLastName",
         "RecipientFirstName",
         "RecipientEmail",
         "ExternalReference",
         "LocationLatitude",
         "LocationLongitude",
         "DistributionChannel",
         "UserLanguage",
         # pertenencia a bloques aleatorizados:
         "FL_21_DO_merit_perc_pref_julio19v01",# bloque 1
         "FL_21_DO_merit_perc_pref_julio19v02",# bloque 2
         "FL_21_DO_merit_perc_pref_julio19v03" # bloque 3 
         )
#  PASO 3: guardar datos
save(study_w01,file = here::here("padsoc-template/01-datos/study_w01.RData"))
```

# Ola 2

```{r prep-wave02, include=FALSE}
# PASO 1: Cargar datos
data <- 
  read_sav(here::here("padsoc-template/99-plantillas/input/Estudio_3_ola2.sav"))

# names(data)

# PASO 2: reordenar variables
study_w02 <- data %>% 
  select(ResponseId,ticket,
         Finished,Progress,
         Intro,
         # preguntas: importancia para salir adelante
         starts_with("get_ah"),
         # Orden - Display Order (DO): importancia para salir adelante
         starts_with("get_ah_DO"),
         # preguntas: escala percepcion y preferencia meritocracia
         starts_with("meritv03_"), 
         # Orden - Display Order (DO): escala percepcion y preferencia meritocracia         
         starts_with("Q177_DO_meritv03"),
         merit_perc_scale,
         Q179_1,
         Q180_1,
         Q175, # Conocimiento sobre pobreza (pre tratamiento)
         # preguntas: escala de igualitarismo
         starts_with("egal_"), 
         # Orden - Display Order (DO): escala de igualitarismo
         starts_with("Q176_DO_egal"),                  
         # preguntas: sociodemograficos
         edad,sexo,edcep,comuna,
         # pertenencia a bloques aleatorizados:
         "FL_6_DO_Tratamiento",            # bloque 1
         "FL_6_DO_Tratamiento_desigualdad",# bloque 2
         "FL_6_DO_Control",                # bloque 3
         # check manipulacion :
         mani_poverty,
         mani_desigualdad,
         mani_placebo,
         # check atencion
         atencion,         
         # tiempos
         starts_with("time_t1"),
         starts_with("time_t2"),
         starts_with("time_ctrl"),
         # informacion de respuesta online
         "StartDate","EndDate",
         "Duration__in_seconds_",
         "RecordedDate",
         "IPAddress",         
         "Status",
         "RecipientLastName",
         "RecipientFirstName",
         "RecipientEmail",
         "ExternalReference",
         "LocationLatitude",
         "LocationLongitude",
         "DistributionChannel",
         "UserLanguage",
         everything()
         )
# names(study_w02)
# sjPlot::view_df(study_w02)

#  PASO 3: guardar datos
save(study_w02,file = here::here("padsoc-template/01-datos/study_w02.RData"))
```

# Ola 3

```{r prep-wave03, include=FALSE}
# PASO 1: Cargar datos
data <- 
  read_sav(here::here("padsoc-template/99-plantillas/input/Estudio_3_ola3.sav"))

names(data)

# PASO 2: reordenar variables
study_w03 <- data %>% 
  select(ResponseId,ticket,
         Finished,Progress,
         # preguntas: importancia para salir adelante
         starts_with("get_ah"),
         # Orden - Display Order (DO): importancia para salir adelante
         starts_with("get_ah_DO"),
         # preguntas: escala percepcion y preferencia meritocracia
         starts_with("meritv03_"), 
         merit_perc_scale,
         Q179_1,
         Q180_1,
         # preguntas: salario percibido y justo:
         sal_perc_1,sal_perc_2,
         sal_just_1=Q190_1,
         sal_just_2=Q190_3,
         # preguntas: escala de igualitarismo
         starts_with("egal_"), 
         # preguntas: escala neoliberalismo
         starts_with("nb_"),
         benefit,
         # preguntas: sociodemograficos
         edad,sexo,edcep,comuna,nacion,nac_otra,
         ess01_1,ess02_1,ess03_1,
         # informacion de respuesta online
         "StartDate","EndDate",
         "Duration__in_seconds_",
         "RecordedDate",
         "IPAddress",         
         "Status",
         "RecipientLastName",
         "RecipientFirstName",
         "RecipientEmail",
         "ExternalReference",
         "LocationLatitude",
         "LocationLongitude",
         "DistributionChannel",
         "UserLanguage",
         everything()
         )
# names(study_w03)
# sjPlot::view_df(study_w03)

#  PASO 3: guardar datos
save(study_w03,file = here::here("padsoc-template/01-datos/study_w03.RData"))
```




